export const CHANGE_SIRKET = "CHANGE_SIRKET";

export const GET_SIRKET_SUCCES = "GET_SIRKET_SUCCES";

export const GET_BIRIM_SUCCESS = "GET_BIRIM_SUCCESS";

export const CREATE_BIRIM_SUCCESS="CREATE_BIRIM_SUCCESS"
export const UPDATE_BIRIM_SUCCESS="UPDATE_BIRIM_SUCCESS"
export const REMOVE_BIRIM = "REMOVE_BIRIM";
